package com.clebs.celerity.utils

enum class DBNames {
    WIND_SCREEN,
    WINDOW_GLASS,
    WIPERS_WASHERS,
    MIRRORS,
    CAB_SECURITY_INTERIOR,
    SEAT_BELT,
    WARNING_SERVICE_LIGHTS,
    FUEL_ADBLUE_LEVEL,
    OIL_COOLANT_LEVEL,
    FOG_LIGHTS,
    INDICATORS_SIDE_REPEATERS,
    HORN_REVERSE_BEEPER,
    STEERING_CONTROL,
    BRAKED_EBS_ABS,
    VEHICLE_LOCKING_SYSTEM,
    BODY_DAMAGE_FRONT,
    BODY_DAMAGE_NEAR_SIDE,
    BODY_DAMAGE_REAR,
    BODY_DAMAGE_OFFSIDE,
    REGISTRATION_NUMBER_PLATES,
    REFLECTORS_MARKERS,
    WHEEL_FIXINGS,
    TYRE_CONDITION_THREAD_DEPTH,
    OIL_FUEL_COOLANT_LEAKS,
    EXCESSIVE_ENG_EXHAUST_SMOKE,
    SPARE_WHEEL
}


