package com.clebs.celerity_admin.models

data class GetWeeklyDefectCheckImagesResponse(
    val BrakeFluidLevelId: Int,
    val EngineCoolantLevelId: Int,
    val PowerSteeringLiquid: Boolean,
    val TyrePressureFrontNS: Boolean? = null,
    val TyrePressureFrontOS: Boolean? = null,
    val TyrePressureRearNS: Boolean? = null,
    val TyrePressureRearOS: Boolean? = null,
    val TyrethreaddepthFrontNSVal: Int,
    val TyrethreaddepthFrontOSVal: Int,
    val TyrethreaddepthRearNSVal: Int,
    val TyrethreaddepthRearOSVal: Int,
    val VdhDefChkImgAddBlueLevel: String,
    val VdhDefChkImgBrakeFluidLevel: String,
    val VdhDefChkImgChkId: Int,
    val VdhDefChkImgEngineCoolantLevel: String,
    val VdhDefChkImgEngineOilLevel: String,
    val VdhDefChkImgId: Int,
    val VdhDefChkImgNswingMirror: String,
    val VdhDefChkImgOilLevelId: Int,
    val VdhDefChkImgOswingMirror: String,
    val VdhDefChkImgPowerSteering: Boolean,
    val VdhDefChkImgTyrePressureFrontNs: String,
    val VdhDefChkImgTyrePressureFrontOs: String,
    val VdhDefChkImgTyrePressureRearNs: String,
    val VdhDefChkImgTyrePressureRearOs: String,
    val VdhDefChkImgTyrethreaddepthFrontNs: String,
    val VdhDefChkImgTyrethreaddepthFrontOs: String,
    val VdhDefChkImgTyrethreaddepthRearNs: String,
    val VdhDefChkImgTyrethreaddepthRearOs: String,
    val VdhDefChkImgVan360Video: String,
    val VdhDefChkImgWindscreenState: Boolean,
    val VdhDefChkImgWindscreenWahingLiquid: Boolean,
    val VdhVerAdminComment: String,
    val WindScreenConditionId: Int,
    val WindowScreenWashingLiquidId: Int
)