name: Build Android APK
on:
  push:
    branches:
      - celerity-osm
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permission
        run: chmod +x ./gradlew

      - name: Build apk
        run: ./gradlew assembleDebug

      - name: Archieve apk
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Install APP Center CLI
        run: npm install -g appcenter-cli

      - name: Upload app on App Center
        run: |
          appcenter login --token ${{ secrets.APPCENTER_TOKEN }}
          appcenter distribute release --app Rohan7300/<CLS> --group CLS-TEST --file app/build/outputs/apk/debug/app-debug.apk
          
